apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cognitive-postgres-bank-0
  namespace: cognitive-bank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
